### ISSUE TITLE
mkdocs build error with python 3.7

### ISSUE THREAD

**Issue by ktamilvanan** [Neoteroi/mkdocs-plugins#22]
I get the following error
```
+ mkdocs build

Traceback (most recent call last):

  File "/usr/local/bin/mkdocs", line 8, in <module>

    sys.exit(cli())

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1128, in __call__

    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1053, in main

    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1659, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1395, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 754, in invoke

    return __callback(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/mkdocs/__main__.py", line 244, in build_command

    from mkdocs.commands import build

  File "/usr/local/lib/python3.7/site-packages/mkdocs/commands/build.py", line 15, in <module>

    from mkdocs.config.defaults import MkDocsConfig

  File "/usr/local/lib/python3.7/site-packages/mkdocs/config/defaults.py", line 4, in <module>

    from mkdocs.config import config_options as c

  File "/usr/local/lib/python3.7/site-packages/mkdocs/config/config_options.py", line 30, in <module>

    import markdown

  File "/usr/local/lib/python3.7/site-packages/markdown/__init__.py", line 29, in <module>

    from .core import Markdown, markdown, markdownFromFile  # noqa: E402

  File "/usr/local/lib/python3.7/site-packages/markdown/core.py", line 26, in <module>

    from . import util

  File "/usr/local/lib/python3.7/site-packages/markdown/util.py", line 87, in <module>

    INSTALLED_EXTENSIONS = metadata.entry_points().get('markdown.extensions', ())

AttributeError: 'EntryPoints' object has no attribute 'get'
```

**Comment by RobertoPrevato** [comment]
Hi @ktamilvanan 
By the look of the stacktrace you shared, this error doesn't occur in my plugin, but in `MkDocs` itself. Anyway even if it occurred because of my plugin, I am personally not going to maintain support for Python 3.7 anymore. A few days ago Python 3.11 was released, and I recommend upgrading, if possible.
